feat: doctest, test cache

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -5,21 +5,36 @@ on:
   - pull_request
 
 jobs:
-  test:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-        python-version: ['3.11']  # Can also test on multiple versions
-
+  pytest:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash -el {0} # setup-miniconda requires bash
     steps:
       - uses: actions/checkout@v4
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
+      - uses: conda-incubator/setup-miniconda@v3
         with:
-          python-version: ${{ matrix.python-version }}
+          miniforge-version: latest
+          activate-environment: test
+      - name: Cache Conda environment
+        id: cache-conda
+        uses: actions/cache@v4
+        env:
+          cache-name: cache-conda
+        with:
+          # npm cache files are stored in `~/.npm` on Linux/macOS
+          path: ~/miniconda3/envs/test
+          key: ${{ runner.os }}-conda-${{ env.cache-name }}-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
+          # restore-keys: |
+          #   ${{ runner.os }}-conda-${{ env.cache-name }}-
+          #   ${{ runner.os }}-conda-
+          #   ${{ runner.os }}-
+      - if: steps.cache-conda.outputs.cache-hit == 'true'
+        run: echo 'conda cache hit!'
       - name: Install dependencies
+        if: steps.cache-conda.outputs.cache-hit != 'true'
         run: |
+          mamba install python=3.11 -y
           python -m pip install --upgrade pip
           pip3 install -r requirements.txt -r requirements_dev.txt
           pip3 install -e .
@@ -49,3 +64,56 @@ jobs:
             # Exit with the exit-code returned by pytest
             exit ${exit_code}
           fi
+
+  doctest:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash -el {0} # setup-miniconda requires bash
+    steps:
+      - uses: actions/checkout@v4
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          miniforge-version: latest
+          activate-environment: test
+      - name: Cache Conda environment
+        id: cache-conda
+        uses: actions/cache@v4
+        env:
+          cache-name: cache-conda
+        with:
+          # npm cache files are stored in `~/.npm` on Linux/macOS
+          path: ~/miniconda3/envs/test
+          key: ${{ runner.os }}-conda-${{ env.cache-name }}-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
+          # restore-keys: |
+          #   ${{ runner.os }}-conda-${{ env.cache-name }}-
+          #   ${{ runner.os }}-conda-
+          #   ${{ runner.os }}-
+      - if: steps.cache-conda.outputs.cache-hit == 'true'
+        run: echo 'conda cache hit!'
+      - name: Install dependencies
+        if: steps.cache-conda.outputs.cache-hit != 'true'
+        run: |
+          mamba install python=3.11 -y
+          python -m pip install --upgrade pip
+          pip3 install -r requirements.txt -r requirements_dev.txt
+          pip3 install -e .
+      - name: Run doctest
+        run: |
+          set +e  # Do not exit shell on pytest failure
+          out=$(python scripts/run_doctest.py 2> stderr.txt)
+          exit_code=$?
+          err=$(<stderr.txt)
+
+          # Display the raw output in the step
+          echo "${out}"
+          echo "${err}"
+
+          # Display the Markdown output in the job summary
+          echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
+          echo "${out}" >> $GITHUB_STEP_SUMMARY
+          echo "${err}" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          # Exit with the exit-code returned by pytest
+
+          exit ${exit_code}
